paths:
  static: public
  uploads: public/uploads

commit_templates:
  - label: Default message
    template_string: '[default_commit_message]'
  - label: Custom message
    template_string: '{message}'

collections_config:
  pages:
    path: src/content/pages
    url: "/[slug]/"
    icon: wysiwyg
    disable_add_folder: true
    _enabled_editors:
      - data
      - visual
    add_options:
      - name: Add New Page
        schema: default
        icon: note_add
    schemas:
      default:
        name: New Page
        path: .cloudcannon/schemas/page.md
    _inputs:
      title:
        type: text
        options:
          required: true
          empty_type: string
      hero:
        type: object
        comment: Hero section content
      about:
        type: object
        comment: About section content
      commitment:
        type: object
        comment: My Commitment section content
      modalities:
        type: object
        comment: Massage Modalities section content

collection_groups:
  - heading: Pages
    collections:
      - pages

_inputs:
  image:
    type: image
    options:
      max_file_size: 5000
  title:
    type: text
    options:
      required: true
  description:
    type: text
  button:
    type: object
    options:
      preview:
        icon: smart_button