paths:
  uploads: public/assets/images
  static: public
collections_config:
  pages:
    path: src/content/pages
    icon: wysiwyg
    url: /[slug]/
    disable_url: false
    _enabled_editors:
      - visual
      - data
    _inputs:
      title:
        type: text
        options:
          empty_type: string
          required: true
        cascade: true
      hero:
        type: object
        comment: Hero section content
        cascade: true
      about:
        type: object
        comment: About section content
        cascade: true
      commitment:
        type: object
        comment: My Commitment section content
        cascade: true
      modalities:
        type: object
        options:
          structures: _structures.modalities
        comment: Massage Modalities section content
        cascade: true
    add_options:
      - name: Add New Page
        icon: note_add
        schema: default
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Page
        icon: notes
collection_groups:
  - heading: Pages
    collections:
      - pages
_structures:
  modalities:
    values:
      - value: 
          title:
          content:
        _inputs:
          title:
            label: Title
          content:
            label: Modalities
            type: array
            options:
              structures: _structures.content
        _structures:
          content:
            values:
              - value:
                  name:
                  description:
                _inputs:
                  description: 
                    type: markdown
_inputs:
  image:
    type: image
    options:
      max_file_size: 5000
    cascade: true
  title:
    type: text
    options:
      required: true
    cascade: true
  description:
    type: text
    cascade: true
  button:
    type: object
    options:
      preview:
        icon: smart_button
    cascade: true
commit_templates:
  - label: Default message
    template_string: '[default_commit_message]'
  - label: Custom message
    template_string: '{message}'
timezone: Etc/UTC
